name: AI Code Review
on: [pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run AI Review
        uses: codium-ai/codium-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
